name: Build and run tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Conan
        uses: conan-io/setup-conan@v1
      - name: Build
        run: |
          sudo apt update && sudo apt install -y libudev-dev
          ./run-build.sh
        shell: bash
