steps:
  - name: Checkout code
    uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - name: Install Conan
    uses: conan-io/setup-conan@v1

  - name: Build
    run: bash ${{github.workspace}}/build.sh
